#!/bin/bash -e

. /usr/share/debconf/confmodule

zs_debug=0

if [ "$1" ]; then
	export LANG=C # avoid locale errors from perl
	ROOT="$1"
	chroot=chroot
	log='log-output -t user-setup'
else
	ROOT=
	chroot=
	log=
fi

db_input critical package-setup/package-path
db_input critical package-setup/hook-path

db_get package-setup/package-path
if [ -d "$RET" ] && [ $zs_debug = 1 ]; then
	echo $RET > /home/zhangsong/pp.log
fi
db_get package-setup/hook-path
if [ -d "$RET" ] && [ $zs_debug = 1 ]; then
	echo $RET >> /home/zhangsong/pp.log
fi